kind: Service
apiVersion: v1
metadata:
  name: {{#APP_NAME#}}
  labels:
    app: {{#APP_NAME#}}
spec:
  selector:
    run: {{#APP_NAME#}}
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{#APP_NAME#}}
spec:
  replicas: 3
  template:
    metadata:
      labels:
        run: {{#APP_NAME#}}
        app: {{#APP_NAME#}}
    spec:
      containers:
      - name: {{#APP_NAME#}}
        image: {{#ACR_NAME#}}.azurecr.io/{{#APP_NAME#}}
        imagePullPolicy: Always
        env:
        - name: KUBE_CONFIG_FILE_PATH
          value: {{#KUBE_CONFIG_FILE_PATH#}}
        ports:
          - containerPort: 80
      imagePullSecrets:
      - name: regsecret